name: CI

on:
  push:
    branches:
      - dev

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled

  merge_group:
    types:
      - checks_requested

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: scripts/rust_fmt.sh --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: scripts/clippy.sh

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2024-01-04 doc

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2024-01-04 test

  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        name: "Rust Toolchain Setup"
        with:
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
        id: "cache-cargo"
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        name: "Download and run cargo-udeps"
        run: |
          wget -O - -c https://github.com/est31/cargo-udeps/releases/download/v0.1.47/cargo-udeps-v0.1.47-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          cargo-udeps-*/cargo-udeps udeps
        env:
          RUSTUP_TOOLCHAIN: nightly-2024-01-04

  all-tests:
    runs-on: ubuntu-latest
    needs:
      - clippy
      - format
      - run-tests
      - udeps
    steps:
      - name: Decide whether all the needed jobs succeeded or failed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
